CMakeLists.txt
config.h
creatureAttr.cpp
creatures.cpp
creatures.h
dm.cpp
files-xml-read.cpp
files-xml-save.cpp
global.h
group.cpp
group.h
misc.cpp
msdp.cpp
msdp.h
quests.cpp
quests.h
room.cpp
rooms.h
staff.cpp
version.h

* Add Daily/Weekly Quests
* Add display (!) of questgiver with available quests
* Keep track of num completions & last completion time

Quest Refresh

---

creature.cpp

Berserking flee bug - K to k

---

player.cpp

Code was checking LT_JAILED and needes to check LT_MOB_JAILED.

fix_mob_jail_auto_free

---

undead.cpp
weaponless.cpp

A long time ago, drain was set to not be allowed to be used in combat. Want to reverse that.

all-liches-to-drainlife-in-combat

---

dmobj.cpp

Set charges

---

dmply.cpp
server.cpp

I put the *award change into this branch. My local repo got jacked somehow.
I fixed it so there's no gp_award like you suggested.

Prevent attack all mobs flag from attacking pets

---

include/config.hpp
include/proto.hpp
players/post.cpp
server/config.cpp
staff/dm.cpp

I looked at the player in combat code as an example...I THINK i got it right. Let me know if I missed anything - it'll be a good learning opportunity.
I didnt update the actual config.xml file with anything new yet.

Add an config option to the game to enable/disable players mudmail staff

---

creatures/monsters.cpp

Better if they just attack. Some mob's don't talk. I.e.
The green slime yells "DIE"
The green slime attacks blah.
:P

Make mobs that attack other mobs stop yelling DIE all the time

---

roguelike/traps.cpp

Forgot to add change of savetype from BRE to DEA.

Lessen dissolve trap evil

---

include/quests.hpp
questing/quests.cpp
xml/quests-xml.cpp

Add AlignmentChange option in quest rewards.

Update quest code

---

commands/cmd.cpp

mithas social!

---

combat/combatSystem.cpp
include/version.hpp
objects/objectAttr.cpp
players/players.cpp
server/login.cpp
staff/dmobj.cpp
xml/creatures-xml.cpp

add slings, knives, scale and ringmail armor

---

areas/startlocs.cpp

Nik doesnt have any way to train liches in Eldinwood, and they don't belong in Eldinwood anyway.

Start location updates

---

creatures/creature.cpp

Old school outdated. Time to get rid of it.

remove drop weapons when flee

---

commands/command5.cpp
commands/communication.cpp
creatures/creatures.cpp
include/communication.hpp
include/config.hpp
include/server.hpp
io/io.cpp
players/player.cpp
server/discordBot.cpp

* Discord /who
* `Who` no longer hides invis/misted players
* Login/Logoff proxies to #in-game

Discord Integration

---

server/login.cpp
staff/dmobj.cpp

Added in newbie weapons for the new weapon types, and added them to the code for *clone also.

Additional stuff for new weapons

---

areas/room.cpp
objects/objects.cpp
players/equipment.cpp

Bane look over this when you get a minute make sure I didn't do anything stupid. I tested it pretty thoroughly this time.
I know i did the if, else if, when i coulda done one statement, but i just think it is easier to read with it.

Fix perm obj random item spawn

---

commands/command5.cpp

Did some local testing, the only issue I found with changestat was that it didn't set mp. Fixed that, can it be enabled now?

enable changestat, set mp

---

include/flags.hpp
include/version.hpp
players/post.cpp
xml/creatures-xml.cpp

Time to remove this restriction.

mudmail staff

---

commands/socials.cpp

Wasn't in there for some reason.

add *A-UPHESHE* to socials

---

creatures/inventory.cpp
include/flags.hpp
include/mudObjects/objects.hpp
io/socket.cpp
objects/object.cpp
players/prefs.cpp

Adds a preference for showing a durability indicator on equipment list, and shows said indicator if said preference is on.

eq durability indicator

---

roguelike/rogues.cpp

Forgot to filter them out on search.

don't search remembered exits

---

objects/objects.cpp

check weightless flag on container before iterating contents

---

combat/combat.cpp
include/version.hpp
players/levelGain.cpp
staff/dmply.cpp

Re-worked chkSave()...Added a crap ton of logging. Also removed all bonus().
Fixed recent bug in *award.

re-work and update chkSave() and fix *award bug

---

combat/combat.cpp
commands/cmd.cpp
include/commands.hpp
include/version.hpp
players/playerInfo.cpp
xml/creatures-xml.cpp

This one is more to provide players better information. Added some additional output, and created a new "checksaves" command.

saves tweaks 2

---

include/httpServer.hpp
server/httpServer.cpp

This is how you get the jwt claims in handlers, see which user made the request etc.

auth context in handlers

---

combat/attack.cpp
include/version.hpp
main/list.cpp
players/player.cpp
xml/creatures-xml.cpp

1. Bumped version to 2.56c
2. Existing Linothan paladins level 13+ now receive hands skill, with initial skill level at their level*9
3. Mage/Lich now always have minimum of 3 daily teleports, even if under level 15, and even if they have shit translocation skill
4. Daily allowed lay on hands bumped from 3 to 5
5. Daily allowed scares bumped from 3 to 5

Misc updates fixes

---

commands/cmd.cpp
commands/communication.cpp
include/flags.hpp
include/global.hpp
include/version.hpp
io/color.cpp
players/prefs.cpp
server/config.cpp

Added sports talk channel to MUD; Including discord webhooks
No more triggering from sports-talk in gossip :P

Add sports talk

---

main/list.cpp

Added the ability to ./List p
Now ez to find who has the most XP and gold..can export to .csv spreadsheet. Just lists: name, level race, class, deity, xp, gold, bank, hpmax, mpmax, str, dex, con, int, pie, and last login. Can add other stuff to list out later if need be.

update list.cpp - list players

---

commands/cmd.cpp
commands/command2.cpp
commands/communication.cpp
creatures/alignment.cpp
creatures/creature.cpp
creatures/creatures.cpp
include/commands.hpp
include/dm.hpp
include/global.hpp
include/mud.hpp
include/mudObjects/container.hpp
include/mudObjects/creatures.hpp
include/proto.hpp
include/quests.hpp
json/quests-json.cpp
magic/divine/healers.cpp
magic/schools/enchantment.cpp
magic/schools/necromancy.cpp
players/player.cpp
questing/quests.cpp
server/access.cpp
server/container.cpp
skills/skillLoader.cpp
staff/dmcrt.cpp
xml/quests-xml.cpp

-alignment code multiple changes and functions (shiftAlignment() setOppositeAllignment(), creature->alignColor(), creature->alignString(), etc...) -added new available languages
-added dmAlignment()
-fixed *set c mon inv # (obj)
-added starstrike attack pre-Mara
-updated roomInfo to find NPC professions

multiple changes

---

commands/communication.cpp

Grrr...The parsing in the speak command got broken, and a couple of the languages weren't working. Completely forgot to test these before last pull. Got bogged down with alignment code. Minor fix. Approve whenever. I doubt anybody is gonna gripe about this, but they might.

Fix language parsing

---

combat/combat.cpp
creatures/monsters.cpp

-Tricked up output
-Added nearEnmPly() check in NO_XP_LOSS check in updateCombat()

debug spawnMonsters

---

combat/die.cpp
include/config.hpp
include/mudObjects/creatures.hpp
server/config.cpp
xml/config-xml.cpp

-Added bonus XP of 10% can turn on/off via config file

Add bonus XP switch to global config file

---

include/paths.hpp
main/updater.cpp

so that they're all driven by BasePath

fix filesystem path references

---

commands/cmd.cpp
commands/command2.cpp
creatures/creature.cpp
creatures/creatures.cpp
include/commands.hpp
include/mudObjects/creatures.hpp
include/proto.hpp
objects/object.cpp
util/misc.cpp

-Added a getHpDurabilityStr() function which returns the strings for various descriptions of damage a player/mob is under
-Modified displayCreature() (which "look" uses) to use getHpDurabilityStr() and added a progress bar as well if a mob is an enemy or if a player has damage.
-Created a general purpose getPercentRemaining(int current, int maximum) which takes those 2 nums and returns a float percentage. The getHpDurabilityStr() function uses it. Modified Object::getDurabilityPercent use this function too.
-Per player request (Tilnar), added cmdCondition() for the "condition" (also "victim") commands - this allows a player to briefly see a mob/player's condition, with progress bar, without having to use look and getting all the other information with it.

QoL additions 01

---

.gitignore
include/mudObjects/objects.hpp
objects/object.cpp
objects/objectAttr.cpp

Label removal

---

include/paths.hpp
main/updater.cpp

Fixes the issue with the Python path that broke effects from the previous attempt

Path references w/ python fix

---

combat/attack.cpp
combat/warriors.cpp
combat/weaponless.cpp
commands/action.cpp
commands/cmd.cpp
creatures/creature.cpp
groups/groups.cpp
include/mud.hpp
magic/magic1.cpp
movement/movement.cpp
players/equipment.cpp
players/player.cpp
players/post.cpp
roguelike/rogues.cpp
roguelike/steal.cpp

-Fixed new mudmail message on login
-Added unread mudmail notification every 10 min
-Auto-stand for everywhere it refused to do something when you were sitting. Except for steal and sneak (since standing unhides)
-New spell shortcuts
mm: magic-missile
fb: fireball
wb: waterbolt
sb: steamblast
ff: flamefill
bb: bloodboil
eg: engulf
et: earth-tremor
cc: cold-cone
cd: cure-disease
sp: slow-poison
cp: cure-poison
cb: cure-blindness
rc: remove-curse

Qol 07142023

---

include/blackjack.hpp
roguelike/blackjack.cpp
roguelike/rogues.cpp

Check for pushes appropriately and only show dealer sum when dealer reveals all cards

Blackjack fixes

---

questing/quests.cpp

Search full display text of quests instead of just the name.

better quest search

---

combat/combatSystem.cpp
combat/die.cpp
commands/command5.cpp
creatures/alignment.cpp
creatures/creatureSkills.cpp
creatures/creatures.cpp
include/flags.hpp
include/login.hpp
include/mudObjects/creatures.hpp
include/mudObjects/objects.hpp
include/proto.hpp
include/version.hpp
magic/divine/healers.cpp
magic/divine/healmagic.cpp
magic/schools/abjuration.cpp
magic/schools/conjuration.cpp
magic/schools/translocation.cpp
magic/schools/transmutation.cpp
objects/objects.cpp
players/player.cpp
roguelike/rogues.cpp
server/demographics.cpp
server/login.cpp

-Finished Mara/Linothan code additions
-Added in deity restrictive object flags and check function
-Added in initial weapon skills for races
-Actually coded in the +% to hide and sneak for racial quirks that I said were already in on the last update (thought they were)
-Added initial weapon skills by race/class at character creation. Will read from the races.xml and classes.xml files in config.
-Loosened alignment restrictions even more.
-Put in a fix for the alignment bug we've been seeing. If it doesn't work after the update, we'll just yank the checks out and make hatesEnemy() not matter until it can be figured out. I think it will now, though. It only will effect people who have to remain neutral, otherwise alignment will change as normal with kills.

Anniversary update mara linothon

---

include/alphanum.hpp
players/player.cpp
util/alphanum.cpp

-Was broken because toNum() isn't working. Changed to std::stoi()

-Fix dice command
