RealmsMud/RealmsCode

creatures/monsters.cpp

The mob jail time is online only, and it's too long. Reducing.

Changing time jailed by mobs to less time

---

roguelike/traps.cpp

Changing it from 5% chance per item to 3% per item, and also adding in a 20% chance to break out of the for loop when checking inventory.
None of this even triggers if the player saves vs traps, so it's rare. But I think it needs to be less harsh than it currently is anyway, even on a failed save.

Lessen_dissolve_item_trap_potential

---

combat/weaponless.cpp
commands/command5.cpp

1) 40sec delay if used in combat w/ mobs...from 90sec
2) 90sec still if not in combat, but + 1/2 of  HP heal # towards MP..so gain MP.
3) changed output strings accordingly

give_monks_love

---

combat/warriors.cpp
magic/divine/healers.cpp

1) Harm touch 10 minutes was 30
2) Harm touch failure = wait 45 sec now
3) Damage increased from x4 to x4-x5
4) Minor output string changes
5) Hands set to same damage as harm
6) Hands now available every 20 minutes - was an hour.

dknight_pal_upgrades

---

movement/movement.cpp

Was set to present tense (i.e. wanders not wandered. floats not floated)
Annoying me. Fixed it.

Fix broken wander grammar

---

roguelike/traps.cpp

Losing inv possessions from an acid trap is very bogus and pisses people off. Made it much rarer, especially for bags.
Could remove it altogether, but these traps are rare enough and in high enough level areas that I think it'll be ok to leave it in.

nerf acid trap

---

combat/attack.cpp

Player may already command pet to stop attacking with by omitting a target: `pet k`, logic for this is above on line 105.
With this additional check, it's easy to get stuck accidentally stopping the attack when you're actually trying to start it, because of the pet assisting you on hit. So just removing that minor inconvenience.

only stop pet attack when there is no target

---

areas/room.cpp
include/mudObjects/exits.hpp
movement/exits.cpp
movement/movement.cpp
xml/exits-xml.cpp

Exits store a list of player ids that have used it if they are hidden, concealed, or desc-only.
If a player is in that list when displaying the room, show the exit and add the (h).

remember exits when used

---

commands/cmd.cpp
staff/dmply.cpp

Fixed it so watchers can now *award.
Watchers can only *award the default XP grant of 1% of current XP, or 500XP, whichever is higher.
Changed it so CTs can now also grant X gold with -g switch. They couldn't before. CTs have 5 minutes between *awards of a player, while watchers must wait 15 minutes.

Update *award command

---

movement/movement.cpp

Just calls `cmdOpen` if the exit is closed.

auto open exits

---

include/flags.hpp
movement/exits.cpp

This is just the flag itself and the logic for it -- it looks like exits.xml would need to be updated too, but I don't have access to the real data. Until the xml gets updated, it will look like the invis flag instead, e.g. `no_remember: 1724 Flags: Hidden(1), Invisible(2).` but it works.

xflag to prevent remembering exit

---

combat/combat.cpp
include/flags.hpp

After reviewing logs, making following adjustments:
Reset time between saves back to 60sec, lowered critical save/fail check chance slightly.
Changed output slightly to not always show critical success/failure unless saves actually goes up.
Removed reporting critical success/failure for LCK save.

chksave() update/tweaks

---

questing/quests.cpp

Adds command to find particular quests in your list.
Also fixes this display order:
```
: que
None!
Old Quests Completed:
None.
Quests in Progress:
```
And fixes this weird one where subsequent commands would have broken formatting after using the main list command:
```
: que aband test
Could not find any quests that matched the name test.
: que view test
Quests matching the name test:
None!
: que aband test
Could not find any quests that matched the name test.
: que
Old Quests Completed:
None.
Quests in Progress:
None!
: que aband test
Could not find any quests that matched the name ^Wtest^x.
```

Quest find and some bugs

---

include/global.hpp
include/version.hpp
magic/schools/translocation.cpp
players/player.cpp
xml/creatures-xml.cpp

Change requested by Charmane asking for more ports.
For mage/lich, ports per day changed to translocation skill level/5, max 10 (10 will be max even after we someday raise the level limit past 40). For now while they can still cast it, other classes always get basic 1 daily port before level 15, and basic 3 after.
Max dimensional anchors allowed increased from 3 to 5.
Also fixed MP costs in teleport spell code. It was all screwed up sometimes costing 50 when is supposed to be:
-30 for teleport self or other
-60 if using an anchor.
Don't know where the 50 was coming from but it's gone now.

mage/lich QoL - ports and anchors

---

combat/warriors.cpp
commands/command5.cpp
creatures/creature.cpp
include/version.hpp
magic/schools/enchantment.cpp

Initial update to fix berserk led to much more:
1) Allow flee when berserk
2) Lower time between berserks based on berserk skill level
3) Lowered the  default time between berserks to 8min from 10min
4) Berserk players now immune to fear/scare
5) Going berserk ends the following effects: fear, hold-person
6) Going berserk breaks the player out of stuns now
7) Removed deity requirements for scare spell - any of them can cast now
8) removed all print() and bonus() in every function i touched
9) bumped version

Update berserk, fear, scare

---

commands/cmd.cpp
commands/command2.cpp
include/commands.hpp
include/flags.hpp
include/mud.hpp
include/version.hpp
players/post.cpp

Player "traffic" command. Let's players check a room for basic info on room traffic. Returns a series of one of two strings, randomly determined, based on "room traffic weight" which is determined by multiplying the room's traffic % with the # of random mob slots that the room has populated.

Player traffic command

---

areas/room.cpp
combat/die.cpp
commands/command2.cpp
commands/communication.cpp
creatures/creature.cpp
creatures/creatureAttr.cpp
creatures/creatures.cpp
effects/effects.cpp
effects/effectsLoader.cpp
include/global.hpp
include/magic.hpp
include/mudObjects/creatures.hpp
include/mudObjects/exits.hpp
magic/magic.cpp
magic/magic1.cpp
magic/schools/abjuration.cpp
magic/schools/conjuration.cpp
magic/schools/transmutation.cpp
movement/exits.cpp
python/mudObject.cpp
roguelike/rogues.cpp
staff/dmcrt.cpp
staff/dmroom.cpp

-Fixes game crash nullptr bug where the wall spells and the knock command were crashing it
-Adds functionality for dispel command to dispel player owned exit and room effects
-Fixes python functionality around permanent exit effects temporarily being dispelled
-Fixes and adds functionality to dispel-magic around exit effects, and also for disintegrate on the wall-of-force exit effect
-Fixes *set xef, *set r eff, and *set c mob eff to again allow setting effects on exits and rooms in game
-Adds wall-of-lightning and wall-of-sleet spells/effects
TODO still:
-Add wall-of-iron, wall-of-ice, and wall-of-stone spells/effects (maybe others)
-Add functionality to dispel-magic to work on room effects
-Adjust/add possible mitigations on where the wall spells can be cast, perhaps using exit size as …

Fix wall spells

---

combat/combatSystem.cpp
include/version.hpp
xml/creatures-xml.cpp

-Existing Linothan clerics will now get parry at max for their current level on login.
-Adjusted parry/riposte to use piety instead of dex for Linothan Clerics. 
-Added newest mob types to riposte code
-Version bump to 2.6.1

Linothan Cleric Parry/Riposte fix

---

include/version.hpp
magic/divine/healers.cpp
xml/creatures-xml.cpp

-Cleric/Assassins were mistakenly given unholyword. Fixes that.
-Fixes targeting in holyword/unholyword so it functions properly 
-Enoch clerics with holyword will get a skill level bump to 75% of max if they are currently below that. 
-Bumped version

misc bug fixes after last update

---

include/version.hpp
magic/divine/healers.cpp

Holyword/Unholyword smite was not granting XP when it fired. Fixed it.

Fix holyword unholyword smite xp bug

---

roguelike/blackjack.cpp

Correctly handle soft aces when displaying sums.
Update displayed sum directly after splitting.
End the game unless player agrees to playing again.

blackjack display fixes
